### ISSUE TITLE
Refactor the landing page to have more content

### ISSUE THREAD

**Issue by nguyenmp** [sexinfo/sexinfo#148]
When people arrive to our website, they don't know if it's porn or sex ed.  This should tell them!

**Comment by Jeffrey711** [comment]
* Move the "About SexInfo Online" section, currently found on the bottom of the landing page, such that it is between the header and the carousel.
* Add our slogan, "A Website Devoted to Sex, Health, & Relationships", to the right of the SexInfo Online logo at the very top of the page.

**Comment by Jeffrey711** [comment]
A new Welcome to SexInfo card has added to the landing page. Our slogan has also been added to the top left below the logo.
