### ISSUE TITLE
Create a tooltip for certain words to provide definitions

### ISSUE THREAD

**Issue by asyung** [sexinfo/sexinfo#156]
So far, this gets test text to show up on hover: 
https://jsfiddle.net/ca7nag07/1/

**Comment by avTester** [comment]
Updated sample code.
• Term is highlighted on hover
• Tooltip displays and fades correctly
• Tooltip's location is anchored to term
https://jsfiddle.net/ca7nag07/2/

**Comment by nguyenmp** [comment]
Thank you avTester.

**Comment by Jeffrey711** [comment]
https://jsfiddle.net/ca7nag07/5/

**Comment by Jeffrey711** [comment]
Updates:
• Added background to tooltip.
• Added border to tooltip (thanks Mark!)
https://jsfiddle.net/ca7nag07/7/

**Comment by Jeffrey711** [comment]
Here's a very simple example that Peter found. Our current sample tooltip is rather fragmented, and I would like to work towards this one instead.

**Comment by Jeffrey711** [comment]
A little more dabbling:
https://jsfiddle.net/ca7nag07/9/

**Comment by Jeffrey711** [comment]
Most bugs squashed in latest commit: 81ac27ec8b8173d851daf22fb5509ef750695cde

There's a problem with the PHP where an out of memory issue is thrown with large taxonomies. Angela found this issue that could be a possible fix:
https://www.drupal.org/node/1898862

**Comment by Jeffrey711** [comment]
Shipped feature!
8b47e9e3d68f0aade852b8724089e6a4f1c3df62
---
In case additional testing is required, here's one of the last iterations I had working on JSFiddle:
https://jsfiddle.net/ca7nag07/11/
