### ISSUE TITLE
Tabling Raffle Page Ideas

### ISSUE THREAD

**Issue by peterlinlin** [sexinfo/sexinfo#157]
* Link on the front page to link to the submit page, next to the word cloud or at the bottom of the page between the elsewhere on the web and about sexinfo online sections

* "Have you seen us? Enter your code here."

* Link all our social media with the submit page.

* submission page, picture of tabling, with message to submit code and info

* after clicking the submit button, a page with "Congratulations/confirmation message" with Instagram photo carousel and links to our other social media, possible message "look for/tag yourself in our photos (or some variation)", test your knowledge link, random article preview or ask sexperts link

**Comment by asyung** [comment]
For the instagram feature, there is instagram block module:
https://www.drupal.org/project/instagram_block

**Comment by Jeffrey711** [comment]
- [ ] Add a JavaScript script that imports Facebook's SDK file.
- [ ] Add HTML embed code for Facebook feed.
- [ ] Install Instagram block module
- [ ] Configure Instagram block module
- [ ] Replace FAQ block on front page with link to Raffle Landing Page
- [ ] Get images from Oscar.
- [ ] Add Twitter stream?

**Comment by Jeffrey711** [comment]
Twitter Embed HTML code:

<a class="twitter-timeline" href="https://twitter.com/sexinfoonline" data-widget-id="699755897132744705">Tweets by @sexinfoonline</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

**Comment by asyung** [comment]
<div class="fb-page" data-href="https://www.facebook.com/SexInfoOnline" data-tabs="timeline" data-width="250" data-height="500" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/SexInfoOnline"><a href="https://www.facebook.com/SexInfoOnline">www.SexInfoOnline.com</a></blockquote></div></div>

**Comment by asyung** [comment]
<a class="twitter-timeline" href="https://twitter.com/sexinfoonline" data-widget-id="699755897132744705">Tweets by @sexinfoonline</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div class="fb-page" data-href="https://www.facebook.com/SexInfoOnline" data-tabs="timeline" data-width="250" data-height="500" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/SexInfoOnline"><a href="https://www.facebook.com/SexInfoOnline">www.SexInfoOnline.com</a></blockquote></div></div>
