### ISSUE TITLE
Split Popular Question Category

### ISSUE THREAD

**Issue by Jeffrey711** [sexinfo/sexinfo#172]
On the "Popular Questions" page, split the "Sexual Difficulties" category into "Male Difficulties" and "Female Difficulties".

**Comment by asyung** [comment]
Do we want to keep the sexual difficulties category and have female/male subcategories? I split them up but there are two questions already in the "sexual difficulties" category that seem to apply to both male and female. I'm not sure if there is a way to put a question in both categories if they wanted to...

**Comment by asyung** [comment]
Tuesday update: would like to revert to one overarching category of Sexual Difficulties. 

*Requested feature would have Sexual Difficulties and three subcategories in the Sexual Difficulties category (Female Difficulties, Male Difficulties, and General Sexual Difficulties)

**Comment by asyung** [comment]
Done!

Added subcategories in questions taxonomy, updated popular questions css file
