### ISSUE TITLE
Receiveupdates typo

### ISSUE THREAD

**Issue by nguyenmp** [sexinfo/sexinfo#177]
"Receiveupdates" should have a space in between the words.

http://www.soc.ucsb.edu/sexinfo/raffle-landing-page

**Comment by Jeffrey711** [comment]
Thank you for your bug report!

Please list the necessary steps to replicate the issue. Also, please state the web browser and version you are using to help us better resolve this issue.

SexInfo can only operate thanks to the support of readers like you. Thank you again!

**Comment by Jeffrey711** [comment]
Dear reader,

Your issue has been resolved. Hope you have a sextastic day!

Signed,
The Sexmasters
