### ISSUE TITLE
2x Gorilla Condoms has extra space

### ISSUE THREAD

**Issue by nguyenmp** [sexinfo/sexinfo#178]
The line item with2 x Gorilla Condoms has an extra space in front of it.
http://www.soc.ucsb.edu/sexinfo/raffle-landing-page

**Comment by Jeffrey711** [comment]
Thank you for your bug report!

Please list the necessary steps to replicate the issue. Also, please state the web browser and version you are using to help us better resolve this issue.

SexInfo can only operate thanks to the support of readers like you. Thank you again!

**Comment by Jeffrey711** [comment]
Dear reader,

Your issue has been resolved. Hope you have a sextastic day!

Signed,
The Sexmasters
