### ISSUE TITLE
Pregnancy flowchart quiz

### ISSUE THREAD

**Issue by andrewberls** [sexinfo/sexinfo#67]
We've discussed having some sort of interactive quiz/flowchart on the site to deter some of the repetitive "Am I Pregnant?" questions that we get.

How this actually implemented is up in the air (and first depends on the writers getting the content together). There may be existing Drupal/javascript plugins for this, but realistically writing a mini quiz/slider thing in jQuery is super easy and more fun anyways.

**Comment by nguyenmp** [comment]
Deployed!  It's called the PPQ.
